name: ece278a
channels:
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - opencv
  - pip
  - scikit-image
  - pip:
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - RISE
